### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by wingman-jr-addon** [wingman-jr-addon/wingman_jr#105]
I'm working slowly towards 3.0. Key video-related issues:

- [x] #52 Basic video scanning support
- [x] #108 Turn video scanning on/off in options
- [x] #113 Tweak on model

Other issues:
- [x] #90 WASM / WebGL choice
- [x] #96 Queue can get stuck - I have a mitigation in #97 , will close if no reproduction of the issue
- [x] #104 Open request cleanup watchdog
- [x] #109 Add feedback link to options page
- [x] #26 Silent mode image replacement
- [x] #115 Update text

And of course:

- [x] Testing

Testing revealed the following issues:
- #117 
- #118
- #119 
- Additionally, #114 was a minor known visual issue

**Comment by wingman-jr-addon** [comment]
3.0.0 is released!
